### PR TITLE
Added functionality for setting up as local server

### PR DESCRIPTION
**Pull request by iambenkay**
Dice game can now be setup on a local server, follow README.md for
instructions
added package.json and and yarn.lock

### CODE REVIEW

**Comment by iambenkay** [comment]
Hello @SlyCreator

**Comment by SlyCreator** [comment]
@iambenkay  can you also setup a live reload to it...

**Comment by iambenkay** [comment]
@SlyCreator as in development? to reload the server whenever it notices a change?

**Comment by SlyCreator** [comment]
whenever the it notice a change in the server file

**Pull request merged**
